[package]
name = "random-approver"
version = "0.1.0"
edition = "2024"
authors = ["Shawon Ashraf"]

[dependencies]
clipboard = "0.5.0"
rand = "0.9.2"
serenity = { version = "0.12.4", features = ["framework", "standard_framework"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
mockall = "0.12.1"
tokio-test = "0.4.3"
