name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: summoner-emoji-bot-x86_64-unknown-linux-gnu
            bin_path: target/x86_64-unknown-linux-gnu/release/summoner-emoji-bot
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            artifact_name: summoner-emoji-bot-x86_64-pc-windows-gnu.exe
            bin_path: target/x86_64-pc-windows-gnu/release/summoner-emoji-bot.exe
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: summoner-emoji-bot-x86_64-apple-darwin
            bin_path: target/x86_64-apple-darwin/release/summoner-emoji-bot
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.bin_path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/summoner-emoji-bot-x86_64-unknown-linux-gnu/summoner-emoji-bot
            artifacts/summoner-emoji-bot-x86_64-pc-windows-gnu.exe/summoner-emoji-bot.exe
            artifacts/summoner-emoji-bot-x86_64-apple-darwin/summoner-emoji-bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
